base_url = "https://filippoguerranti.com"
title = "Filippo Guerranti"
description = "Filippo Guerranti's personal website"
author = "Filippo Guerranti"
compile_sass = true
build_search_index = false
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags" }]

theme = "apollo"

[markdown]
highlight_code = true
external_links_target_blank = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]


[extra]
theme = "toggle" # options: auto, toggle
favicon = "/icons/favicon.ico"
toc = true
fancy_code = true
mathjax = true
mathjax_dollar_inline_enable = true

# Font configuration
# Options: "charter", "lora", "source-serif-pro", "crimson-text", "playfair-display", "merriweather", "system-serif", "zed" (original)
font_family = "charter"

# Primary color configuration
# Set custom primary colors for light and dark themes
primary_color_light = "#60a5fa"  # Custom blue for light theme
primary_color_dark = "#60a5fa"   # Custom lighter blue for dark theme

# Case configuration
case_mode = "lowercase"  # Options: "normal", "lowercase"

socials = [
  { name = "X", url = "https://x.com/guerrantif", icon = "x-twitter" },
  { name = "GitHub", url = "https://github.com/guerrantif/", icon = "github" },
  { name = "LinkedIn", url = "https://www.linkedin.com/in/filippoguerranti/", icon = "linkedin" },
  { name = "Scholar", url = "https://scholar.google.com/citations?user=uekwkvYAAAAJ", icon = "google-scholar" }
]

menu = [
  { name = "/Papers", url = "/papers", weight = 1 },
  { name = "/Posts", url = "/posts", weight = 2 },
  { name = "/Contact", url = "/contact", weight = 3 },
]
