name: Deploy Zola site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Zola
        uses: taiki-e/install-action@zola

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Zola
        run: zola build

      - name: Compress static assets
        run: |
          # Find and compress CSS, JS, HTML, SVG, and other text files
          find ./public -type f \( -name "*.css" -o -name "*.js" -o -name "*.html" -o -name "*.svg" -o -name "*.json" -o -name "*.xml" -o -name "*.txt" \) | while read file; do
            gzip -9 -c "$file" > "$file.gz"
            # Replace original with compressed version and add proper headers
            mv "$file.gz" "$file"
          done
          
          echo "Compression complete. File sizes:"
          find ./public -type f -name "*.css" -o -name "*.js" -o -name "*.html" | head -5 | xargs ls -lh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
